DEFAULT_CONFIG = {
    "exp_dir": "exp_stage_a10",
    "checkpoint": None,
    "words_path": "data/words.txt",
    "text_path": "data/texts.txt",
    "pairs_path": "data/pairs.csv",
    "charset_path": "data/charset.txt",
    "max_words": 1_500_000,
    "eval_ratio": 0.01,
    "max_len": 32,
    "emb_size": 192,
    "n_layers": 6,
    "n_heads": 6,
    "ffn_size": 768,
    "dropout": 0.1,
    "batch_size": 256,
    "epochs": 100,
    "lr": 1e-3,
    "min_len": 3,
    "mask_prob": 0.5,
    "span_min": 1,
    "span_max": 3,
    "spans_min": 1, 
    "spans_max": 2,
    "weight_decay": 0.01,
    "grad_clip": 1.0,
    "ngram_probs": {1: 0.5, 2: 0.3, 3: 0.2},
    "steps_per_epoch": 1_500_000,
    "seed": 42,
    "mask_threshold": 0.05,
    "apply_threshold": 0.95,
    "max_edits": 1,
    "sub_threshold": 50,
}
